const europeClubFilter = 'FILTER (\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Albania ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Andorra ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Azerbaijan ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Belarus ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Belgium ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Bosnia_and_Herzegovina ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Bulgaria ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Croatia ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Cyprus ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Czech_Republic ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Finland ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Germany ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Greece ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Hungary ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Iceland ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Italy ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Kazakhstan ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_in_the_Kingdom_of_the_Netherlands ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Kosovo ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Latvia ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Liechtenstein ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Lithuania ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Luxembourg ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Malta ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Moldova ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Monaco ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Montenegro ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Norway ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Poland ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Portugal ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Romania ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Russia ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_San_Marino ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Scotland ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Slovakia ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Slovenia ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Spain ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Switzerland ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Denmark ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Georgia ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Serbia ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Ukraine ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_United_Kingdom ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Vatican_City ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Estonia ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_France ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Armenia ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Austria ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_the_Republic_of_Macedonia ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Sweden ||\n' +
  '?football_clubs_in_country = dbc:Football_clubs_in_Wales\n' +
')'

module.exports = europeClubFilter
